import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./_providers/AuthProvider";
import { Toaster } from "sonner";
import { FormProvider } from "./(auth)/FormProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`max-w-[1440px] m-auto ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <FormProvider>{children}</FormProvider>
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}
